language: node_js
node_js:
  - '8'

jobs:
  include:
    - stage: deploy
      before_install: cd frontend-react
      provider: firebase
      token:
        secure: "1//01QaCswrK88a-CgYIARAAGAESNwF-L9IrOfFHMiOcns2j-KAyQAF2C7cN9CdI_8iPz3gLJ1gy1Lp1ENZY_hoUnA5Psl3-BaCJPCE"