language: node_js
node_js:
  - '8'

warnings_are_errors: false
before_install: "cd frontend-react"

install:
  - npm install
script:
  - CI=false npm run build

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "1//0fZBWMvRXC2ViCgYIARAAGA8SNwF-L9Iry0AgcMchyUw0AyrCqpUwt-Kw6JJAHWd1ySs7TvR4JNh5bGJpma4079z1mRTlZWNe_co"