language: node_js
node_js:
  - '8'

jobs:
  include:
    - stage: deploy to heroku
      before_install: cd backend-nodejs
      deploy: &heroku
        provider: heroku
        app: pshare-jacky
        api_key: 2e2bdfaf-981b-4986-948a-5e4b01094b06
    - stage: deploy
      name: deploy to firebase
      before_install: cd frontend-react
      before_script: npm install firebase-tools -g
      script:
        CI=false npm run build
        firebase deploy --only hosting --token "1//01QaCswrK88a-CgYIARAAGAESNwF-L9IrOfFHMiOcns2j-KAyQAF2C7cN9CdI_8iPz3gLJ1gy1Lp1ENZY_hoUnA5Psl3-BaCJPCE"

